baseURL = 'http://opensimcreator.com'
languageCode = 'en-us'
title = 'OpenSim Creator'
staticDir = 'static'

[menu]
[[menu.main]]
    identifier = 'about'
    name = 'Home'
    pre = '<i class="bi bi-house"></i>'
    url = '/'
    weight = -110
[[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    pre = '<i class="bi bi-camera"></i>'
    url = '/gallery/'
    weight = -105
[[menu.main]]
    identifier = 'youtube'
    name = 'YouTube'
    pre = '<i class="bi bi-youtube"></i>'
    url = 'https://www.youtube.com/playlist?list=PLOPlDtRLhp8c2SWLCQKKd-l4__UainOYk'
    weight = -100
#[[menu.main]]
#    identifier = 'docs'
#    name = 'Docs'
#    pre = '<i class="bi bi-book"></i>'
#    url = '/doc/'
#    weight = -90
